#!/bin/bash
set -euo pipefail

if [ "${DEBUG:-}" = 1 ]; then
    set -x
    docker build -t mycdk .
else
    docker build -t mycdk . >/dev/null
fi

[ -z ${CDK_EMQX_CLUSTERNAME+x} ] &&
    CDK_EMQX_CLUSTERNAME=$(git config --get user.name | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')

docker run -e AWS_PROFILE="${AWS_PROFILE:-default}" \
       -e CDK_EMQX_CLUSTERNAME=${CDK_EMQX_CLUSTERNAME} \
       --rm -it \
       -v ~/.aws:/root/.aws:ro \
       -v $(pwd):/opt/ \
       -w /opt \
       mycdk "$@"
