# config file version
apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: localhost:5432
    database: postgres
    user: grafana
    secureJsonData:
      password: "grafana"
    jsonData:
      sslmode: "disable"
      timescaledb: false

  - name: "Prometheus"
    type: "prometheus"
    url: "http://localhost:9090"
    access: "proxy"
    basicAuth: false
