# Note: this is just for local testing, it's not used in the final CDK
# deployment
version: "3.4"
services:
  db_host:
    network_mode: host
    build: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/tmp/postgres

  prometheus:
    network_mode: host
    image: "prom/prometheus:latest"

  grafana:
    network_mode: host
    build: grafana
    depends_on:
      - db_host
      - prometheus
