name: Create and publish a Docker images

on:
  workflow_dispatch:

  push:
    branches: ['main', 'master']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for grafana container
        id: grafana-meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/k32/perf-test-grafana

      - name: Extract metadata (tags, labels) for postgres container
        id: postgres-meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/k32/perf-test-postgres

      - name: Build and push Grafana docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker-images/grafana
          push: true
          tags: ${{ steps.grafana-meta.outputs.tags }}
          labels: ${{ steps.grafana-meta.outputs.labels }}

      - name: Build and push Postgres docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker-images/postgres
          push: true
          tags: ${{ steps.postgres-meta.outputs.tags }}
          labels: ${{ steps.postgres-meta.outputs.labels }}
